# Generated by Django 4.1.4 on 2022-12-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookMyShowApp', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_cinema_halls', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='movies/posters')),
                ('description', models.CharField(max_length=512)),
                ('duration', models.TimeField()),
                ('language', models.CharField(choices=[('english', 'ENGLISH'), ('hindi', 'HINDI')], max_length=255)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('action', 'ACTION'), ('thriller', 'THRILLER'), ('comedy', 'COMEDY'), ('horror', 'HORROR'), ('suspense', 'SUSPENSE')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_seats', models.PositiveIntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookMyShowApp.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_duration', models.DateTimeField()),
                ('end_duration', models.DateTimeField()),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookMyShowApp.movie')),
            ],
        ),
    ]
