# Generated by Django 4.1.4 on 2022-12-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookMyShowApp', '0003_cinema_city_movie_screens_screenmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookMyShowApp.city'),
            preserve_default=False,
        ),
    ]
