# Generated by Django 4.1.4 on 2022-12-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMyShowApp', '0005_screenmovie_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenmovie',
            name='end_duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='screenmovie',
            name='start_duration',
            field=models.TimeField(),
        ),
    ]
