# Generated by Django 4.1.4 on 2022-12-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookMyShowApp', '0006_alter_screenmovie_end_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenmovie',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookMyShowApp.cinema'),
            preserve_default=False,
        ),
    ]
