# Generated by Django 4.1.4 on 2022-12-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMyShowApp', '0008_seat_screenmovie_total_seats_capacity_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenmovie',
            name='total_seats_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
