# Generated by Django 4.1.4 on 2022-12-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMyShowApp', '0012_seat_movie_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
