# Generated by Django 4.1.4 on 2022-12-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMyShowApp', '0015_delete_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenmovie',
            name='seat_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
