# Generated by Django 4.1.4 on 2022-12-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMyShowApp', '0016_screenmovie_seat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_block_duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
