# Generated by Django 4.1.4 on 2023-01-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMyShowApp', '0017_booking_seat_block_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_data', models.JSONField(default={})),
            ],
        ),
    ]
